version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Current directory contents:"
      - ls -F
      - echo "Installing dependencies..."
      - if [ -d "frontend" ]; then cd frontend && npm install; else npm install; fi

  build:
    commands:
      - echo "Building project..."
      - if [ -d "frontend" ]; then cd frontend && npm run build; else npm run build; fi

  post_build:
    commands:
      - echo "Deploying to S3..."
      - if [ -d "frontend" ]; then cd frontend && aws s3 sync build/ s3://$S3_BUCKET_FRONTEND --delete; else aws s3 sync build/ s3://$S3_BUCKET_FRONTEND --delete; fi
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: 'frontend/build'
